apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGODB_URI: bG9sIGhhaGEgdSB0aG90
  JWT_SECRET: aSBsaWtlIGNhdHMgYW5kIGtpdHRpZXM=
# stringData:
#   CLIENT_IP: "http://localhost:80"
  



